homeassistant:
  # Name of the location where Home Assistant is running
  name: Our House
  # Location required to calculate the time the sun rises and sets
  latitude: !secret my_latitude
  longitude: !secret my_longitude  

  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 108
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  # Customization file
  customize: !include customize.yaml

http:
  base_url: !secret my_url 
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem  
  
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Components with !include
automation: !include_dir_list automation
script: !include_dir_merge_named script
group: !include groups.yaml
zone: !include zones.yaml
device_tracker: !include device_tracker.yaml
light: !include light_groups.yaml
switch: !include switches.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
notify: !include notifiers.yaml   

# Panel for Floor Plan https://github.com/pkozul/ha-floorplan
panel_custom:
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:home
    url_path: floorplan
    config: !include floorplan.yaml

# Lovelace Card Custom Updater
custom_updater:

discovery:
  ignore:
    - igd

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Wake on LAN 
wake_on_lan:

# Inputs
input_boolean:
  guest_mode:
    name: Guest Mode On
    icon: mdi:account-switch
  morning_heat:
    name: Morning Heat On
    icon: mdi:thermometer-lines
  evening_dehumidifier:
    name: Activate Dehumidifier
    icon: mdi:water   
  

input_number:
  garage_closed:
    name: Garage Closed Repetition
    min: -5
    max: 5
    step: 1         
  wyze_notification:
    name: Pause Wyze Notification - Frank
    min: 0
    max: 240
    step: 15  
    unit_of_measurement: minutes
    icon: mdi:camera  
    
input_datetime:
  hum_off:
    name: Humidifier Time Off
    has_date: false
    has_time: true
  hum_on:
    name: Humidifier Time On
    has_date: false
    has_time: true
    
    
# Timers    
timer:
  heater_off:
    duration: '01:30:00' 
  coffee_off:
    duration: '02:30:00'       
  wyze_pause_frank:
    duration: '01:00:00'  
  wyze_pause_kathy:
    duration: '01:00:00'     
    
# Sensors

    
# Text to speech
tts:
  - platform: google
 
## Amazon AWS Components
aws:
  credentials:
    - name: my_aws_account
      aws_access_key_id: !secret aws_key_id
      aws_secret_access_key: !secret aws_secret_key
  notify:
    # use the first credential defined in aws component by default
    - name: aws_lambda_1
      aws_access_key_id: !secret aws_key_id
      aws_secret_access_key: !secret aws_secret_key
      service: lambda
      region_name: us-west-2
      
## GOOGLE ===================     
## Google Calendar
google:
  client_id: !secret google_cal_id
  client_secret: !secret google_cal_secret 
  
## Google HOME
googlehome:
  devices:
    - host: 192.168.1.122  
    # - host: 192.168.1.148
    # - host: 192.168.1.141  
    # - host: 192.168.1.117
    # - host: 192.168.1.113
  
#Cloud
# cloud:
  # google_actions:
    # filter:
      # include_domains:
        # - switch
        # - light
        # - script
        # - media_player  
  
## GOOGLE ===================
  
lutron_caseta:
  host: 192.168.1.106
  keyfile: /ssl/lutron/caseta.key
  certfile: /ssl/lutron/caseta.crt
  ca_certs: /ssl/lutron/caseta-bridge.crt  

##ifttt Configuration
ifttt:
  key: !secret ifttt_key  
  
# Dark Sky Weather
weather:
  - platform: darksky
    api_key: !secret darksky_key
    units: us
    mode: daily  
    
# Python
python_script:

## Media Players
media_player:
  # Denon AVR
  - platform: denonavr
    host: 192.168.1.107
    name: Denon Main
    show_all_sources: True
    timeout: 2
    zones:
      - zone: Zone2
        name: Denon Remote
  # LG WebOS    
  - platform: webostv
    host: 192.168.1.125
    name: LG TV
    turn_on_action:
      service: wake_on_lan.send_magic_packet
      data:
        mac: "44-FE-3B-30-24-A2"    
    customize:
      sources:
        - Roku
        - Chromecast
        - Live TV

# Custom Components
retirement_countdown:
  wrkg_days: 'refreshing ... '
  commute_miles: 'refreshing ... '  
  next_vacation: 'refreshing ... '
  update_time: 'refreshing ... '    
