- platform: clicksend
  name: ClickSend
  username: !secret click_user
  api_key: !secret click_api
  recipient: !secret click_recip
- platform: pushbullet
  name: pushbullet
  api_key: !secret push_bullet_key
- platform: hangouts
  name: hangout_notifier
  default_conversations:
    - id: Ugz_DG8s_6WoV637g1l4AaABAagBxZzMDw
    - id: Ugzo_ICgyVEfNSDse9l4AaABAagBnrGgBA
    - id: Ugw7aWMpGN9ki28Q_ON4AaABAagBsIriAw   
- platform: webostv
  host: 192.168.1.125
  name: lg_tv
  filename: webostv.conf 
- platform: html5
  name: html_notifier
  vapid_pub_key: !secret vapid_pub_key
  vapid_prv_key: !secret vapid_prv_key
  vapid_email: !secret vapid_email