id: coffee brew
alias: Coffee Brewing
initial_state: true
trigger:
- platform: webhook
  webhook_id: 9CAA2BA12E56F242D34B3BEC199396E9F4EC7751DF5F5EDE85DF75C482WK1
action:
# Turn on Coffee pot
- service: switch.turn_on
  entity_id: switch.aeon_coffee
# Turn off Wyze cam notifications for next 45 minutes
# until I am done snoozing.  
- data:
    entity_id: input_number.wyze_notification_frank
    value: 45
  service: input_number.set_value  
   

