id: mazda bt off
alias: Mazda BT Off
trigger:
- platform: webhook
  webhook_id: 9CAA2BA12E56F242D34B3BEC199396E9F4EC7751DF5F5EDE85DF75C482BT0
action:
- data:
    payload: 'OFF'
    retain: '1'
    topic: phone/bluetooth
  service: mqtt.publish
initial_state: 'on'