id: mazda bt on
alias: Mazda BT On
trigger:
- platform: webhook
  webhook_id: 9CAA2BA12E56F242D34B3BEC199396E9F4EC7751DF5F5EDE85DF75C482BT1
action:
- data:
    payload: 'ON'
    retain: '1'
    topic: phone/bluetooth
  service: mqtt.publish
initial_state: 'on'