# This webhook accepts the RETURN of data from an AWS lambda function that
# takes travel time and does a timedelta on now() to create an ETA.  It then
# posts back to HASS at this hook, including data to be used in an SMS alert.
# The alert will be sent with ClickSend.
id: send waze_eta 
alias: Send Waze ETA
initial_state: 'on'
trigger:
- platform: webhook
  webhook_id: 9CAA2BA12E56F242D34B3BEC199396E9F4EC7751DF5F5EDE85DF75C482AWS3
action:
- data_template:
    event: waze_eta
    value1: '{{trigger.json.message}}'
  service: ifttt.trigger