id: sunrise
alias: Sunrise Routine
trigger:   
  platform: numeric_state
  entity_id: sun.sun
  value_template: "{{ state.attributes.elevation }}"
  # Can be a positive or negative number
  above: -4.0 
  below: -2.0
condition:
  condition: time
  # Can only fire in the morning
  after: '00:00:00' 
  before: '12:00:00'
action:
- service: light.turn_off
  entity_id: light.exterior_front_door, light.patio_back_door, light.dining_room_tree
# Turn garage reminder notifications back off if someone is home
- data:
    entity_id: input_boolean.garage_reminder_on
  service_template: >-
    {% if is_state("group.home","home") %}
      input_boolean.turn_off
    {% else %}
      homeassistant.update_entity
    {% endif %} 
# Turn Wyze Cam notifications back on
- service: ifttt.trigger
  data: {"event":"notify_on", "value1":"Hello World!"} 
# send solar angle to google sheet
- service: ifttt.trigger
  data_template: {"event":"solar_angle", 
    "value1": '{{state_attr("sun.sun", "elevation")}}', 
    "value2": '{{ (as_timestamp(states.sun.sun.attributes.next_rising) - as_timestamp(now()))/60 }}',
    "value3": '{{as_timestamp(now())|timestamp_custom("%I:%M:%S %p")}}'}  
