# This webhook automation accepts a post from an IFTTT recipe named "Denon Volume Set".
# The recipe posts to this webhook with data to be passed to python_script.denon_volume.

id: denon volume
alias: Denon Volume Select
initial_state: 'on'
trigger:
- platform: webhook
  webhook_id: 9CAA2BA12E56F242D34B3BEC199396E9F4EC7751DF5F5EDE85DF75C482DENVOL
action:
- data_template:
    volume_command: '{{trigger.json.volume_command}}'
    direction: '{{trigger.json.direction}}'
  service: python_script.denon_volume

# The "volume_command" is a string of text words to be parsed.  It may
# contain both directional words such as "up" or "down", as well as
# words to indicate the desired setting such as "to 54", or "by 5%",
# or "up a bit".  "direction" may be "increase", "decrease", or "parse", 
# which means the script should figure it out.
    
  