id: Family_Room_Sunset
alias: Family Room Lights Sunset
initial_state: 'on'
trigger:
- event: sunset
  offset: -01:30:00
  platform: sun
condition:
- condition: state
  entity_id: group.home
  state: home
action:
# Use cloud cover to determine when to start the automation.
# More cloud cover, shorter delay.
- delay: >
    {% if states.sensor.dark_sky_cloud_coverage.state | int > 80 %}
      00:00:00
    {% elif states.sensor.dark_sky_cloud_coverage.state | int > 60 %}
      00:15:00
    {% elif states.sensor.dark_sky_cloud_coverage.state | int > 40 %}
      00:30:00
    {% elif states.sensor.dark_sky_cloud_coverage.state | int > 20 %}      
      00:45:00
    {% else %}
      01:00:00
    {% endif %}

# Track % Cloud Cover and time lights come on in Google Sheet    
- service: ifttt.trigger
  data_template: {"event":"sunset_cloud_cover", 
    "value1": '{{states.sensor.dark_sky_cloud_coverage.state | int}}', 
    "value2": '{{as_timestamp(now())|timestamp_custom("%I:%M:%S %p")}}',
    "value3": '{{ ((as_timestamp(states.sun.sun.attributes.next_setting) - as_timestamp(now()))/60 ) | int }}'}      
    
# Trigger an automation to bring them both up to 30% in 5 min.
- event: start_fam_room_sunset
  event_data:
    entity_id: light.family_room_chair_lamp
- event: start_fam_room_sunset
  event_data:
    entity_id: light.family_room_sofa_lamp
# Wait for the 5 minute fade up to 30%    
- delay: '00:06:00'
# Now that both are at a starting brightness, slow fade to 100%
- service: python_script.light_fader
  data:
    entity_id: light.family_room_chair_lamp
    end_level_pct: 100
    transition: '00:40:00'
# - delay: '00:00:02'
- service: python_script.light_fader
  data:
    entity_id: light.family_room_sofa_lamp
    end_level_pct: 100
    transition: '00:40:00'
