id: Family_Room_Sunset
alias: Family Room Lights Sunset
initial_state: 'on'
trigger:
- event: sunset
  offset: -01:00:00
  platform: sun
condition:
- condition: state
  entity_id: group.home
  state: home
action:
- service: python_script.light_fader
  data:
    entity_id: light.family_room_chair_lamp
    start_level_pct: 30
    end_level_pct: 100
    transition: '01:15:00'
- delay: '00:00:02'
- service: python_script.light_fader
  data:
    entity_id: light.family_room_sofa_lamp
    start_level_pct: 30
    end_level_pct: 100
    transition: '01:15:00'
