id: night stand lights
alias: Night Stand Lights
trigger: 
- platform: state 
  entity_id: light.master_bedroom_night_stand
  to: 'on'
- platform: state 
  entity_id: light.master_bedroom_night_stand
  to: 'off'
action:
- data:
    entity_id: switch.kitchen_tree
  service_template: > 
    {% if trigger.from_state.state == trigger.to_state.state %}
      homeassistant.update_entity
    {% else %}
      switch.turn_{{states("light.master_bedroom_night_stand")}}
    {% endif %}
    
# Added "for" one second to potentially address issue with 
# light.master_bedroom_night_stand flashing with brightness changes. The 
# theory is that triggering a service many times in a short period was
# perhaps causing the behavior.
    