id: exterior_sunrise
alias: Exterior Lights Off at Dawn
trigger:   
  platform: sun
  event: sunrise
  offset: '-00:20:00'  
action:
- service: light.turn_off
  entity_id: light.exterior_front_door, light.patio_back_door
  