id: random_lights_chair_lamp
alias: Random Away Lights Chair Lamp

trigger:
- entity_id: group.home
  platform: state
  to: 'not_home' 
- event: sunset
  offset: 00:00:00
  platform: sun
  
condition:
- condition: state
  entity_id: group.home
  state: not_home
- condition: state
  entity_id: input_boolean.guest_mode
  state: 'off'   
- condition: time
  before: '22:59:00'
- condition: sun
  after: sunset
  after_offset: "00:00:00"   

action:
- entity_id: light.family_room_chair_lamp
  service_template: >
    {%- if (states("group.home") == 'home' or
      now().hour | int >= 23) or 
      state_attr("sun.sun", "above_horizon") == 'above_horizon' -%}
      homeassistant.update_entity
    {%- else -%}
      light.turn_on  
    {%- endif -%}
- delay: >
    {%- if (states("group.home") == 'home' or
      now().hour | int >= 23) or 
      state_attr("sun.sun", "above_horizon") == 'above_horizon' -%}
      00:00:03
    {%- else -%}
      00:{{ range(10,59) | random | int }}:00
    {%- endif -%}
- entity_id: light.family_room_chair_lamp
  service_template: >
    {%- if states("group.home") == 'home' -%}   
      homeassistant.update_entity 
    {%- elif (states("light.upstairs_lights") == 'on') -%}
      light.turn_off
    {%- else -%}
      homeassistant.update_entity
    {%- endif -%}

- delay: >
    {%- if (states("group.home") == 'home' or
      now().hour | int >= 23) or 
      state_attr("sun.sun", "above_horizon") == 'above_horizon' -%}
      00:00:03
    {%- else -%}
      00:{{ range(10,59) | random | int }}:00
    {%- endif -%}
- entity_id: light.family_room_chair_lamp
  service_template: >
    {%- if (states("group.home") == 'home' or
      now().hour | int >= 23) or 
      state_attr("sun.sun", "above_horizon") == 'above_horizon' -%}
      homeassistant.update_entity
    {%- else -%}
      light.turn_on  
    {%- endif -%}
- delay: >
    {%- if (states("group.home") == 'home' or
      now().hour | int >= 23) or 
      state_attr("sun.sun", "above_horizon") == 'above_horizon' -%}
      00:00:03
    {%- else -%}
      00:{{ range(10,59) | random | int }}:00
    {%- endif -%}
- entity_id: light.family_room_chair_lamp
  service_template: >
    {%- if states("group.home") == 'home' -%}   
      homeassistant.update_entity 
    {%- elif (states("light.upstairs_lights") == 'on') -%}
      light.turn_off
    {%- else -%}
      homeassistant.update_entity
    {%- endif -%}

- delay: >
    {%- if (states("group.home") == 'home' or
      now().hour | int >= 23) or 
      state_attr("sun.sun", "above_horizon") == 'above_horizon' -%}
      00:00:03
    {%- else -%}
      00:{{ range(10,59) | random | int }}:00
    {%- endif -%}
- entity_id: light.family_room_chair_lamp
  service_template: >
    {%- if (states("group.home") == 'home' or
      now().hour | int >= 23) or 
      state_attr("sun.sun", "above_horizon") == 'above_horizon' -%}
      homeassistant.update_entity
    {%- else -%}
      light.turn_on  
    {%- endif -%}
- delay: >
    {%- if (states("group.home") == 'home' or
      now().hour | int >= 23) or 
      state_attr("sun.sun", "above_horizon") == 'above_horizon' -%}
      00:00:03
    {%- else -%}
      00:{{ range(10,59) | random | int }}:00
    {%- endif -%}
- entity_id: light.family_room_chair_lamp
  service_template: >
    {%- if states("group.home") == 'home' -%}   
      homeassistant.update_entity 
    {%- elif (states("light.upstairs_lights") == 'on') -%}
      light.turn_off
    {%- else -%}
      homeassistant.update_entity
    {%- endif -%}

- delay: >
    {%- if (states("group.home") == 'home' or
      now().hour | int >= 23) or 
      state_attr("sun.sun", "above_horizon") == 'above_horizon' -%}
      00:00:03
    {%- else -%}
      00:{{ range(10,59) | random | int }}:00
    {%- endif -%}
- entity_id: light.family_room_chair_lamp
  service_template: >
    {%- if (states("group.home") == 'home' or
      now().hour | int >= 23) or 
      state_attr("sun.sun", "above_horizon") == 'above_horizon' -%}
      homeassistant.update_entity
    {%- else -%}
      light.turn_on  
    {%- endif -%}
- delay: >
    {%- if (states("group.home") == 'home' or
      now().hour | int >= 23) or 
      state_attr("sun.sun", "above_horizon") == 'above_horizon' -%}
      00:00:03
    {%- else -%}
      00:{{ range(10,59) | random | int }}:00
    {%- endif -%}
- entity_id: light.family_room_chair_lamp
  service_template: >
    {%- if states("group.home") == 'home' -%}   
      homeassistant.update_entity 
    {%- elif (states("light.upstairs_lights") == 'on') -%}
      light.turn_off
    {%- else -%}
      homeassistant.update_entity
    {%- endif -%}

- delay: >
    {%- if (states("group.home") == 'home' or
      now().hour | int >= 23) or 
      state_attr("sun.sun", "above_horizon") == 'above_horizon' -%}
      00:00:03
    {%- else -%}
      00:{{ range(10,59) | random | int }}:00
    {%- endif -%}
- entity_id: light.family_room_chair_lamp
  service_template: >
    {%- if (states("group.home") == 'home' or
      now().hour | int >= 23) or 
      state_attr("sun.sun", "above_horizon") == 'above_horizon' -%}
      homeassistant.update_entity
    {%- else -%}
      light.turn_on  
    {%- endif -%}
- delay: >
    {%- if (states("group.home") == 'home' or
      now().hour | int >= 23) or 
      state_attr("sun.sun", "above_horizon") == 'above_horizon' -%}
      00:00:03
    {%- else -%}
      00:{{ range(10,59) | random | int }}:00
    {%- endif -%}
- entity_id: light.family_room_chair_lamp
  service_template: >
    {%- if states("group.home") == 'home' -%}   
      homeassistant.update_entity 
    {%- elif (states("light.upstairs_lights") == 'on') -%}
      light.turn_off
    {%- else -%}
      homeassistant.update_entity
    {%- endif -%}

- delay: >
    {%- if (states("group.home") == 'home' or
      now().hour | int >= 23) or 
      state_attr("sun.sun", "above_horizon") == 'above_horizon' -%}
      00:00:03
    {%- else -%}
      00:{{ range(10,59) | random | int }}:00
    {%- endif -%}
- entity_id: light.family_room_chair_lamp
  service_template: >
    {%- if (states("group.home") == 'home' or
      now().hour | int >= 23) or 
      state_attr("sun.sun", "above_horizon") == 'above_horizon' -%}
      homeassistant.update_entity
    {%- else -%}
      light.turn_on  
    {%- endif -%}
- delay: >
    {%- if (states("group.home") == 'home' or
      now().hour | int >= 23) or 
      state_attr("sun.sun", "above_horizon") == 'above_horizon' -%}
      00:00:03
    {%- else -%}
      00:{{ range(10,59) | random | int }}:00
    {%- endif -%}
- entity_id: light.family_room_chair_lamp
  service_template: >
    {%- if states("group.home") == 'home' -%}   
      homeassistant.update_entity 
    {%- elif (states("light.upstairs_lights") == 'on') -%}
      light.turn_off
    {%- else -%}
      homeassistant.update_entity
    {%- endif -%}

- delay: >
    {%- if (states("group.home") == 'home' or
      now().hour | int >= 23) or 
      state_attr("sun.sun", "above_horizon") == 'above_horizon' -%}
      00:00:03
    {%- else -%}
      00:{{ range(10,59) | random | int }}:00
    {%- endif -%}
- entity_id: light.family_room_chair_lamp
  service_template: >
    {%- if (states("group.home") == 'home' or
      now().hour | int >= 23) or 
      state_attr("sun.sun", "above_horizon") == 'above_horizon' -%}
      homeassistant.update_entity
    {%- else -%}
      light.turn_on  
    {%- endif -%}
- delay: >
    {%- if (states("group.home") == 'home' or
      now().hour | int >= 23) or 
      state_attr("sun.sun", "above_horizon") == 'above_horizon' -%}
      00:00:03
    {%- else -%}
      00:{{ range(10,59) | random | int }}:00
    {%- endif -%}
- entity_id: light.family_room_chair_lamp
  service_template: >
    {%- if states("group.home") == 'home' -%}   
      homeassistant.update_entity 
    {%- elif (states("light.upstairs_lights") == 'on') -%}
      light.turn_off
    {%- else -%}
      homeassistant.update_entity
    {%- endif -%}

- delay: >
    {%- if (states("group.home") == 'home' or
      now().hour | int >= 23) or 
      state_attr("sun.sun", "above_horizon") == 'above_horizon' -%}
      00:00:03
    {%- else -%}
      00:{{ range(10,59) | random | int }}:00
    {%- endif -%}
- entity_id: light.family_room_chair_lamp
  service_template: >
    {%- if (states("group.home") == 'home' or
      now().hour | int >= 23) or 
      state_attr("sun.sun", "above_horizon") == 'above_horizon' -%}
      homeassistant.update_entity
    {%- else -%}
      light.turn_on  
    {%- endif -%}
- delay: >
    {%- if (states("group.home") == 'home' or
      now().hour | int >= 23) or 
      state_attr("sun.sun", "above_horizon") == 'above_horizon' -%}
      00:00:03
    {%- else -%}
      00:{{ range(10,59) | random | int }}:00
    {%- endif -%}
- entity_id: light.family_room_chair_lamp
  service_template: >
    {%- if states("group.home") == 'home' -%}   
      homeassistant.update_entity 
    {%- elif (states("light.upstairs_lights") == 'on') -%}
      light.turn_off
    {%- else -%}
      homeassistant.update_entity
    {%- endif -%}

- delay: >
    {%- if (states("group.home") == 'home' or
      now().hour | int >= 23) or 
      state_attr("sun.sun", "above_horizon") == 'above_horizon' -%}
      00:00:03
    {%- else -%}
      00:{{ range(10,59) | random | int }}:00
    {%- endif -%}
- entity_id: light.family_room_chair_lamp
  service_template: >
    {%- if (states("group.home") == 'home' or
      now().hour | int >= 23) or 
      state_attr("sun.sun", "above_horizon") == 'above_horizon' -%}
      homeassistant.update_entity
    {%- else -%}
      light.turn_on  
    {%- endif -%}
- delay: >
    {%- if (states("group.home") == 'home' or
      now().hour | int >= 23) or 
      state_attr("sun.sun", "above_horizon") == 'above_horizon' -%}
      00:00:03
    {%- else -%}
      00:{{ range(10,59) | random | int }}:00
    {%- endif -%}
- entity_id: light.family_room_chair_lamp
  service_template: >
    {%- if states("group.home") == 'home' -%}   
      homeassistant.update_entity 
    {%- elif (states("light.upstairs_lights") == 'on') -%}
      light.turn_off
    {%- else -%}
      homeassistant.update_entity
    {%- endif -%}

- delay: >
    {%- if (states("group.home") == 'home' or
      now().hour | int >= 23) or 
      state_attr("sun.sun", "above_horizon") == 'above_horizon' -%}
      00:00:03
    {%- else -%}
      00:{{ range(10,59) | random | int }}:00
    {%- endif -%}
- entity_id: light.family_room_chair_lamp
  service_template: >
    {%- if (states("group.home") == 'home' or
      now().hour | int >= 23) or 
      state_attr("sun.sun", "above_horizon") == 'above_horizon' -%}
      homeassistant.update_entity
    {%- else -%}
      light.turn_on  
    {%- endif -%}
- delay: >
    {%- if (states("group.home") == 'home' or
      now().hour | int >= 23) or 
      state_attr("sun.sun", "above_horizon") == 'above_horizon' -%}
      00:00:03
    {%- else -%}
      00:{{ range(10,59) | random | int }}:00
    {%- endif -%}
- entity_id: light.family_room_chair_lamp
  service_template: >
    {%- if states("group.home") == 'home' -%}   
      homeassistant.update_entity 
    {%- else -%}
      light.turn_off
    {%- endif -%}    
