id: At_Church
alias: At Church
trigger:
- entity_id: device_tracker.google_maps_109448847750537552828
  event: enter
  platform: zone
  zone: zone.church
action:
- data:
    message: At_Church
  service: notify.pushbullet
initial_state: true