id: '1537815832783'
alias: At Work
trigger:
- entity_id: device_tracker.google_maps_109448847750537552828
  event: enter
  platform: zone
  zone: zone.work
condition: []
action:
- data:
    message: At work
  service: notify.pushbullet