id: all_gone_stuff_on
alias: Home - All Gone Stuff On
# If after 15 minutes of nobody home there are any items 
# left on in the group.not_home_on, send an SMS alert.  
# The template selects which script to run based on whether
# or not it is during the random away lights time frame
initial_state: 'on'
trigger:
- entity_id: group.home
  platform: state
  to: 'not_home'
  for:
    hours: 0
    minutes: 15
    seconds: 0
condition:
  condition: template
  value_template: '{{ is_state("group.not_home_on", "on") }}'
action:
  service_template: >
    {%- if (now().day == (as_timestamp(states.sun.sun.attributes.next_setting)|timestamp_custom("%d")|int))
        or (now().hour | int == 23) -%} 
      script.all_gone_not_random
    {%- else -%}
      script.all_gone_random
    {%- endif -%}