id: Left_Church
alias: Left Church
trigger:
- entity_id: device_tracker.google_maps_109448847750537552828
  event: leave
  platform: zone
  zone: zone.church
action:
- data:
    message: Left_Church
  service: notify.pushbullet
initial_state: true