id: random_lights_begin
alias: Random Away Lights Begin

trigger:
- entity_id: group.home
  platform: state
  to: 'not_home'
- event: sunset
  offset: 00:00:00
  platform: sun

condition:
- condition: state
  entity_id: group.home
  state: not_home
- condition: state
  entity_id: input_boolean.guest_mode
  state: 'off'
- condition: time
  before: '22:59:00'
- condition: sun
  after: sunset
  after_offset: "00:00:00"

action:
- service: script.random_lights_night_stand
- service: script.random_lights_kitchen_table

