id: work_zone_phone_settings
alias: Work Zone Phone Settings
trigger:
- entity_id: device_tracker.google_maps_109448847750537552828
  event: enter
  platform: zone
  zone: zone.work
- entity_id: device_tracker.google_maps_109448847750537552828
  event: leave
  platform: zone
  zone: zone.work  
condition: []
action:
- data_template:
    message: >-
      {% if trigger.event == "enter" %}
        At work
      {% else %}
        Left work        
      {% endif %}    
  service: notify.pushbullet